# Generated by Django 5.0 on 2024-07-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_alter_usergroup_group_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usergroup',
            name='group_name',
            field=models.CharField(choices=[('friends', 'friends'), ('family', 'family'), ('special', 'special'), ('office', 'office'), ('school', 'school'), ('university', 'university'), ('onetoone', 'onetoone'), ('superuser', 'superuser'), ('bhaibrother', 'bhaibrother')], max_length=500),
        ),
    ]
