# Generated by Django 5.0 on 2024-07-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_alter_usergroup_group_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
