# Generated by Django 5.0 on 2024-07-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0007_alter_chatting_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatting',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
